services:

  #    todoservice:
  #        build:
  #            context: ./bigtodo
  #            dockerfile: Dockerfile
  #        ports:
  #            - "8080:8080"

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: adouglas
#      MONGO_INITDB_ROOT_PASSWORD: password1234

volumes:
  mongodb:
    external: true